"""Incremental graph update logic.

Detects changed files via git diff, re-parses only changed + impacted files,
and updates the graph accordingly. Also supports CLI invocation for hooks.
"""

from __future__ import annotations

import concurrent.futures
import fnmatch
import hashlib
import logging
import os
import re
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Optional

from .graph import GraphStore
from .parser import CodeParser

_MAX_PARSE_WORKERS = int(os.environ.get(
    "CRG_PARSE_WORKERS", str(min(os.cpu_count() or 4, 8))
))

logger = logging.getLogger(__name__)

# Default ignore patterns (in addition to .gitignore)
DEFAULT_IGNORE_PATTERNS = [
    ".code-review-graph/**",
    "node_modules/**",
    ".git/**",
    "__pycache__/**",
    "*.pyc",
    ".venv/**",
    "venv/**",
    "dist/**",
    "build/**",
    ".next/**",
    "target/**",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "*.db",
    "*.sqlite",
    "*.db-journal",
    "*.db-wal",
]


def find_repo_root(start: Path | None = None) -> Optional[Path]:
    """Walk up from start to find the nearest .git directory."""
    current = start or Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    if (current / ".git").exists():
        return current
    return None


def find_project_root(start: Path | None = None) -> Path:
    """Find the project root: git repo root if available, otherwise cwd."""
    root = find_repo_root(start)
    if root:
        return root
    return start or Path.cwd()


def get_db_path(repo_root: Path) -> Path:
    """Determine the database path for a repository.

    Creates the ``.code-review-graph/`` directory and an inner ``.gitignore``
    (with ``*``) so generated files are never committed.  If a legacy
    ``.code-review-graph.db`` exists at the repo root the database is migrated
    into the new directory (WAL/SHM side-files are discarded).
    """
    crg_dir = repo_root / ".code-review-graph"
    new_db = crg_dir / "graph.db"

    # Ensure directory exists
    crg_dir.mkdir(exist_ok=True)

    # Auto-create .gitignore inside the directory (idempotent)
    inner_gitignore = crg_dir / ".gitignore"
    if not inner_gitignore.exists():
        inner_gitignore.write_text(
            "# Auto-generated by code-review-graph — do not commit database files.\n"
            "# The graph.db contains absolute paths and code structure metadata.\n"
            "*\n"
        )

    # Migrate legacy database if present
    legacy_db = repo_root / ".code-review-graph.db"
    if legacy_db.exists() and not new_db.exists():
        legacy_db.rename(new_db)
    # Discard stale WAL/SHM side-files from the old location
    for suffix in ("-wal", "-shm", "-journal"):
        side = repo_root / f".code-review-graph.db{suffix}"
        if side.exists():
            side.unlink()

    return new_db


def _load_ignore_patterns(repo_root: Path) -> list[str]:
    """Load ignore patterns from .code-review-graphignore file."""
    patterns = list(DEFAULT_IGNORE_PATTERNS)
    ignore_file = repo_root / ".code-review-graphignore"
    if ignore_file.exists():
        for line in ignore_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                patterns.append(line)
    return patterns


def _should_ignore(path: str, patterns: list[str]) -> bool:
    """Check if a path matches any ignore pattern."""
    return any(fnmatch.fnmatch(path, p) for p in patterns)


def _is_binary(path: Path) -> bool:
    """Quick heuristic: check if file appears to be binary."""
    try:
        chunk = path.read_bytes()[:8192]
        return b"\x00" in chunk
    except (OSError, PermissionError):
        return True


_GIT_TIMEOUT = int(os.environ.get("CRG_GIT_TIMEOUT", "30"))  # seconds, configurable


def _git_branch_info(repo_root: Path) -> tuple[str, str]:
    """Return (branch_name, head_sha) for the current repo state."""
    branch = ""
    sha = ""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=_GIT_TIMEOUT,
        )
        if result.returncode == 0:
            branch = result.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=_GIT_TIMEOUT,
        )
        if result.returncode == 0:
            sha = result.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return branch, sha

_SAFE_GIT_REF = re.compile(r"^[A-Za-z0-9_.~^/@{}\-]+$")


def get_changed_files(repo_root: Path, base: str = "HEAD~1") -> list[str]:
    """Get list of changed files via git diff."""
    if not _SAFE_GIT_REF.match(base):
        logger.warning("Invalid git ref rejected: %s", base)
        return []
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", base, "--"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        if result.returncode != 0:
            # Fallback: try diff against empty tree (initial commit)
            result = subprocess.run(
                ["git", "diff", "--name-only", "--cached"],
                capture_output=True,
                text=True,
                cwd=str(repo_root),
                timeout=_GIT_TIMEOUT,
            )
        files = [f.strip() for f in result.stdout.splitlines() if f.strip()]
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_staged_and_unstaged(repo_root: Path) -> list[str]:
    """Get all modified files (staged + unstaged + untracked)."""
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        files = []
        for line in result.stdout.splitlines():
            if len(line) > 3:
                entry = line[3:].strip()
                # Handle renamed files: "R  old -> new"
                if " -> " in entry:
                    entry = entry.split(" -> ", 1)[1]
                files.append(entry)
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_all_tracked_files(repo_root: Path) -> list[str]:
    """Get all files tracked by git."""
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        return [f.strip() for f in result.stdout.splitlines() if f.strip()]
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def collect_all_files(repo_root: Path) -> list[str]:
    """Collect all parseable files in the repo, respecting ignore patterns."""
    ignore_patterns = _load_ignore_patterns(repo_root)
    parser = CodeParser()
    files = []

    # Prefer git ls-files for tracked files
    tracked = get_all_tracked_files(repo_root)
    if tracked:
        candidates = tracked
    else:
        # Fallback: walk directory
        candidates = [
            str(p.relative_to(repo_root))
            for p in repo_root.rglob("*")
            if p.is_file()
        ]

    for rel_path in candidates:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        full_path = repo_root / rel_path
        if not full_path.is_file():
            continue
        if full_path.is_symlink():
            continue
        if parser.detect_language(full_path) is None:
            continue
        if _is_binary(full_path):
            continue
        files.append(rel_path)

    return files


_MAX_DEPENDENT_HOPS = int(os.environ.get("CRG_DEPENDENT_HOPS", "2"))
_MAX_DEPENDENT_FILES = 500


def _single_hop_dependents(store: GraphStore, file_path: str) -> set[str]:
    """Find files that directly depend on *file_path* (single hop)."""
    dependents: set[str] = set()
    edges = store.get_edges_by_target(file_path)
    for e in edges:
        if e.kind == "IMPORTS_FROM":
            dependents.add(e.file_path)

    nodes = store.get_nodes_by_file(file_path)
    for node in nodes:
        for e in store.get_edges_by_target(node.qualified_name):
            if e.kind in ("CALLS", "IMPORTS_FROM", "INHERITS", "IMPLEMENTS"):
                dependents.add(e.file_path)

    dependents.discard(file_path)
    return dependents


def find_dependents(
    store: GraphStore,
    file_path: str,
    max_hops: int = _MAX_DEPENDENT_HOPS,
) -> list[str]:
    """Find files that import from or depend on the given file.

    Performs up to *max_hops* iterations of expansion (default 2).
    Stops early if the total exceeds 500 files.
    """
    all_dependents: set[str] = set()
    visited: set[str] = {file_path}
    frontier: set[str] = {file_path}
    for _hop in range(max_hops):
        next_frontier: set[str] = set()
        for fp in frontier:
            deps = _single_hop_dependents(store, fp)
            new_deps = deps - visited
            all_dependents.update(new_deps)
            next_frontier.update(new_deps)
        visited.update(next_frontier)
        frontier = next_frontier
        if not frontier:
            break
        if len(all_dependents) > _MAX_DEPENDENT_FILES:
            logger.warning(
                "Dependent expansion capped at %d files for %s",
                len(all_dependents), file_path,
            )
            # Truncate to the cap
            return list(all_dependents)[:_MAX_DEPENDENT_FILES]
    return list(all_dependents)


def _parse_single_file(
    args: tuple[str, str],
) -> tuple[str, list, list, str | None, str]:
    """Parse one file in a worker process.

    Returns ``(rel_path, nodes, edges, error_or_none, file_hash)``.
    Must be a module-level function so ``ProcessPoolExecutor`` can
    serialise it across processes.
    """
    rel_path, repo_root_str = args
    abs_path = Path(repo_root_str) / rel_path
    try:
        raw = abs_path.read_bytes()
        fhash = hashlib.sha256(raw).hexdigest()
        parser = CodeParser()
        nodes, edges = parser.parse_bytes(abs_path, raw)
        return (rel_path, nodes, edges, None, fhash)
    except Exception as e:
        return (rel_path, [], [], str(e), "")


def full_build(repo_root: Path, store: GraphStore) -> dict:
    """Full rebuild of the entire graph."""
    parser = CodeParser()
    files = collect_all_files(repo_root)

    # Purge stale data from files no longer on disk
    existing_files = set(store.get_all_files())
    current_abs = {str(repo_root / f) for f in files}
    for stale in existing_files - current_abs:
        store.remove_file_data(stale)

    total_nodes = 0
    total_edges = 0
    errors = []
    file_count = len(files)

    use_serial = os.environ.get("CRG_SERIAL_PARSE", "") == "1"

    if use_serial or file_count < 8:
        # Serial fallback (for debugging or tiny repos)
        for i, rel_path in enumerate(files, 1):
            full_path = repo_root / rel_path
            try:
                source = full_path.read_bytes()
                fhash = hashlib.sha256(source).hexdigest()
                nodes, edges = parser.parse_bytes(full_path, source)
                store.store_file_nodes_edges(str(full_path), nodes, edges, fhash)
                total_nodes += len(nodes)
                total_edges += len(edges)
            except (OSError, PermissionError) as e:
                errors.append({"file": rel_path, "error": str(e)})
            except Exception as e:
                logger.warning("Error parsing %s: %s", rel_path, e)
                errors.append({"file": rel_path, "error": str(e)})
            if i % 50 == 0 or i == file_count:
                logger.info("Progress: %d/%d files parsed", i, file_count)
    else:
        # Parallel parsing — store calls remain serial (SQLite single-writer)
        args_list = [(rel_path, str(repo_root)) for rel_path in files]
        with concurrent.futures.ProcessPoolExecutor(
            max_workers=_MAX_PARSE_WORKERS,
        ) as executor:
            for i, (rel_path, nodes, edges, error, fhash) in enumerate(
                executor.map(_parse_single_file, args_list, chunksize=20), 1,
            ):
                if error:
                    logger.warning("Error parsing %s: %s", rel_path, error)
                    errors.append({"file": rel_path, "error": error})
                    continue
                full_path = repo_root / rel_path
                store.store_file_nodes_edges(
                    str(full_path), nodes, edges, fhash,
                )
                total_nodes += len(nodes)
                total_edges += len(edges)
                if i % 200 == 0 or i == file_count:
                    logger.info("Progress: %d/%d files parsed", i, file_count)

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "full")
    branch, sha = _git_branch_info(repo_root)
    if branch:
        store.set_metadata("git_branch", branch)
    if sha:
        store.set_metadata("git_head_sha", sha)
    store.commit()

    return {
        "files_parsed": len(files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "errors": errors,
    }


def incremental_update(
    repo_root: Path,
    store: GraphStore,
    base: str = "HEAD~1",
    changed_files: list[str] | None = None,
) -> dict:
    """Incremental update: re-parse changed + dependent files only."""
    parser = CodeParser()
    ignore_patterns = _load_ignore_patterns(repo_root)

    # Determine changed files
    if changed_files is None:
        changed_files = get_changed_files(repo_root, base)

    if not changed_files:
        return {
            "files_updated": 0,
            "total_nodes": 0,
            "total_edges": 0,
            "changed_files": [],
            "dependent_files": [],
        }

    # Find dependent files (files that import from changed files)
    dependent_files: set[str] = set()
    for rel_path in changed_files:
        full_path = str(repo_root / rel_path)
        deps = find_dependents(store, full_path)
        for d in deps:
            # Convert back to relative path if needed
            try:
                dependent_files.add(str(Path(d).relative_to(repo_root)))
            except ValueError:
                dependent_files.add(d)

    # Combine changed + dependent
    all_files = set(changed_files) | dependent_files

    total_nodes = 0
    total_edges = 0
    errors = []

    # Separate deleted/unparseable files from files that need re-parsing
    to_parse: list[str] = []
    for rel_path in all_files:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        abs_path = repo_root / rel_path
        if not abs_path.is_file():
            store.remove_file_data(str(abs_path))
            continue
        if parser.detect_language(abs_path) is None:
            continue
        # Quick hash check to skip unchanged files
        try:
            raw = abs_path.read_bytes()
            fhash = hashlib.sha256(raw).hexdigest()
            existing_nodes = store.get_nodes_by_file(str(abs_path))
            if existing_nodes and existing_nodes[0].file_hash == fhash:
                continue
        except (OSError, PermissionError):
            pass
        to_parse.append(rel_path)

    use_serial = os.environ.get("CRG_SERIAL_PARSE", "") == "1"

    if use_serial or len(to_parse) < 8:
        for rel_path in to_parse:
            abs_path = repo_root / rel_path
            try:
                source = abs_path.read_bytes()
                fhash = hashlib.sha256(source).hexdigest()
                nodes, edges = parser.parse_bytes(abs_path, source)
                store.store_file_nodes_edges(str(abs_path), nodes, edges, fhash)
                total_nodes += len(nodes)
                total_edges += len(edges)
            except (OSError, PermissionError) as e:
                errors.append({"file": rel_path, "error": str(e)})
            except Exception as e:
                logger.warning("Error parsing %s: %s", rel_path, e)
                errors.append({"file": rel_path, "error": str(e)})
    else:
        args_list = [(rel_path, str(repo_root)) for rel_path in to_parse]
        with concurrent.futures.ProcessPoolExecutor(
            max_workers=_MAX_PARSE_WORKERS,
        ) as executor:
            for rel_path, nodes, edges, error, fhash in executor.map(
                _parse_single_file, args_list, chunksize=20,
            ):
                if error:
                    logger.warning("Error parsing %s: %s", rel_path, error)
                    errors.append({"file": rel_path, "error": error})
                    continue
                store.store_file_nodes_edges(
                    str(repo_root / rel_path), nodes, edges, fhash,
                )
                total_nodes += len(nodes)
                total_edges += len(edges)

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "incremental")
    branch, sha = _git_branch_info(repo_root)
    if branch:
        store.set_metadata("git_branch", branch)
    if sha:
        store.set_metadata("git_head_sha", sha)
    store.commit()

    return {
        "files_updated": len(all_files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "changed_files": list(changed_files),
        "dependent_files": list(dependent_files),
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# Watch mode
# ---------------------------------------------------------------------------


_DEBOUNCE_SECONDS = 0.3
_WATCH_LOCK_FILE = "watch.lock"
_WATCH_PID_FILE = "watch.pid"
_WATCH_LOG_FILE = "watch-daemon.log"


def _watch_runtime_dir(repo_root: Path) -> Path:
    """Return the runtime directory used by watcher metadata files."""
    get_db_path(repo_root)
    return repo_root / ".code-review-graph"


def _watch_lock_path(repo_root: Path) -> Path:
    return _watch_runtime_dir(repo_root) / _WATCH_LOCK_FILE


def _watch_pid_path(repo_root: Path) -> Path:
    return _watch_runtime_dir(repo_root) / _WATCH_PID_FILE


def _watch_log_path(repo_root: Path) -> Path:
    return _watch_runtime_dir(repo_root) / _WATCH_LOG_FILE


def _is_pid_running(pid: int) -> bool:
    """Return True if a process with *pid* appears alive."""
    if pid <= 0:
        return False
    if os.name == "nt":
        try:
            win_flags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
            result = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}"],
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
                creationflags=win_flags,
            )
            out = (result.stdout or "") + (result.stderr or "")
            if str(pid) in out:
                return True
        except OSError:
            pass
    try:
        os.kill(pid, 0)
        return True
    except PermissionError:
        # A live process can still reject signal probes.
        return True
    except OSError:
        return False


def _read_pid_file(path: Path) -> int | None:
    try:
        return int(path.read_text().strip())
    except (OSError, ValueError):
        return None


def _write_pid_file(repo_root: Path, pid: int) -> None:
    _watch_pid_path(repo_root).write_text(f"{pid}\n")


def _remove_pid_file(repo_root: Path) -> None:
    try:
        _watch_pid_path(repo_root).unlink()
    except OSError:
        pass


def _acquire_watch_lock(repo_root: Path, owner_pid: int) -> tuple[bool, str]:
    """Acquire single-writer lock for watch mode.

    Returns ``(acquired, reason)``.
    """
    lock_path = _watch_lock_path(repo_root)

    if lock_path.exists():
        lock_pid = _read_pid_file(lock_path)
        if lock_pid and _is_pid_running(lock_pid):
            return False, f"watcher already running (pid={lock_pid})"
        try:
            lock_path.unlink()
        except OSError:
            return False, "failed to clear stale watch lock"

    try:
        fd = os.open(str(lock_path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        with os.fdopen(fd, "w", encoding="utf-8") as lock_file:
            lock_file.write(f"{owner_pid}\n")
        return True, "acquired"
    except FileExistsError:
        return False, "watch lock is already held"
    except OSError as exc:
        return False, f"failed to create watch lock: {exc}"


def _release_watch_lock(repo_root: Path, owner_pid: int) -> None:
    lock_path = _watch_lock_path(repo_root)
    lock_pid = _read_pid_file(lock_path)
    if lock_pid is not None and lock_pid != owner_pid:
        return
    try:
        lock_path.unlink()
    except OSError:
        pass


def get_watch_daemon_status(repo_root: Path) -> dict:
    """Return daemon/watch status for the repository."""
    pid_path = _watch_pid_path(repo_root)
    lock_path = _watch_lock_path(repo_root)
    daemon_pid = _read_pid_file(pid_path)
    lock_pid = _read_pid_file(lock_path)
    daemon_running = bool(daemon_pid and _is_pid_running(daemon_pid))
    lock_active = bool(lock_pid and _is_pid_running(lock_pid))
    return {
        "running": daemon_running,
        "pid": daemon_pid,
        "lock_active": lock_active,
        "lock_pid": lock_pid,
        "pid_file": str(pid_path),
        "lock_file": str(lock_path),
    }


def start_watch_daemon(repo_root: Path) -> dict:
    """Start offline watch daemon process for the repository."""
    status = get_watch_daemon_status(repo_root)
    if status["running"]:
        return {
            "started": False,
            "pid": status["pid"],
            "message": f"Watch daemon already running (pid={status['pid']})",
        }

    py_exe = sys.executable
    if os.name == "nt":
        pyw = Path(sys.executable).with_name("pythonw.exe")
        if pyw.exists():
            py_exe = str(pyw)

    cmd = [
        py_exe,
        "-m",
        "code_review_graph.cli",
        "daemon",
        "start",
        "--repo",
        str(repo_root),
        "--foreground",
    ]

    env = os.environ.copy()
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = (
        f"{repo_root}{os.pathsep}{existing}" if existing else str(repo_root)
    )

    log_path = _watch_log_path(repo_root)
    if os.name == "nt":
        subprocess.Popen(
            cmd,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            close_fds=True,
            cwd=str(repo_root),
            env=env,
            creationflags=(
                subprocess.DETACHED_PROCESS
                | subprocess.CREATE_NEW_PROCESS_GROUP
                | getattr(subprocess, "CREATE_NO_WINDOW", 0)
            ),
        )
    else:
        with log_path.open("a", encoding="utf-8") as log_file:
            subprocess.Popen(
                cmd,
                stdin=subprocess.DEVNULL,
                stdout=log_file,
                stderr=log_file,
                close_fds=True,
                cwd=str(repo_root),
                env=env,
                start_new_session=True,
            )

    pid_path = _watch_pid_path(repo_root)
    for _ in range(100):
        pid = _read_pid_file(pid_path)
        if pid and _is_pid_running(pid):
            return {
                "started": True,
                "pid": pid,
                "message": f"Watch daemon started (pid={pid})",
            }
        time.sleep(0.1)

    return {
        "started": False,
        "pid": None,
        "message": (
            f"Watch daemon start timed out. Check {log_path} "
            "or run 'code-review-graph daemon start --foreground'."
        ),
    }


def stop_watch_daemon(repo_root: Path) -> dict:
    """Stop offline watch daemon process for the repository."""
    pid = _read_pid_file(_watch_pid_path(repo_root))
    if not pid:
        _remove_pid_file(repo_root)
        return {"stopped": False, "message": "Watch daemon is not running."}

    if not _is_pid_running(pid):
        _remove_pid_file(repo_root)
        _release_watch_lock(repo_root, pid)
        return {"stopped": False, "message": "Watch daemon was stale; cleaned up metadata."}

    try:
        if os.name == "nt":
            win_flags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
            subprocess.run(
                ["taskkill", "/PID", str(pid), "/T", "/F"],
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
                creationflags=win_flags,
            )
        else:
            os.kill(pid, signal.SIGTERM)
    except OSError as exc:
        return {"stopped": False, "message": f"Failed to stop watch daemon: {exc}"}

    for _ in range(20):
        if not _is_pid_running(pid):
            break
        time.sleep(0.1)

    _remove_pid_file(repo_root)
    _release_watch_lock(repo_root, pid)
    return {"stopped": True, "message": f"Watch daemon stopped (pid={pid})."}


def run_watch_daemon_foreground(repo_root: Path) -> None:
    """Run watch daemon loop in foreground (internal entrypoint)."""
    _write_pid_file(repo_root, os.getpid())
    db_path = get_db_path(repo_root)
    store = GraphStore(db_path)
    try:
        watch(repo_root, store, owner_pid=os.getpid())
    finally:
        _remove_pid_file(repo_root)
        store.close()


def watch(repo_root: Path, store: GraphStore, owner_pid: int | None = None) -> None:
    """Watch for file changes and auto-update the graph.

    Uses a 300ms debounce to batch rapid-fire saves into a single update.
    """
    import threading

    from watchdog.events import FileSystemEventHandler
    from watchdog.observers import Observer

    parser = CodeParser()
    ignore_patterns = _load_ignore_patterns(repo_root)
    owner_pid = owner_pid or os.getpid()

    acquired, reason = _acquire_watch_lock(repo_root, owner_pid)
    if not acquired:
        raise RuntimeError(f"Unable to start watcher: {reason}")

    try:
        class GraphUpdateHandler(FileSystemEventHandler):
            def __init__(self):
                self._pending: set[str] = set()
                self._lock = threading.Lock()
                self._timer: threading.Timer | None = None

            def _should_handle(self, path: str) -> bool:
                if Path(path).is_symlink():
                    return False
                try:
                    rel = str(Path(path).relative_to(repo_root))
                except ValueError:
                    return False
                if _should_ignore(rel, ignore_patterns):
                    return False
                if parser.detect_language(Path(path)) is None:
                    return False
                return True

            def on_modified(self, event):
                if event.is_directory:
                    return
                if self._should_handle(event.src_path):
                    self._schedule(event.src_path)

            def on_created(self, event):
                if event.is_directory:
                    return
                if self._should_handle(event.src_path):
                    self._schedule(event.src_path)

            def on_deleted(self, event):
                if event.is_directory:
                    return
                # Only handle files we would normally track
                try:
                    rel = str(Path(event.src_path).relative_to(repo_root))
                except ValueError:
                    return
                if _should_ignore(rel, ignore_patterns):
                    return
                try:
                    store.remove_file_data(event.src_path)
                    store.commit()
                    logger.info("Removed: %s", rel)
                except Exception as e:
                    logger.error("Error removing %s: %s", rel, e)

            def _schedule(self, abs_path: str):
                """Add file to pending set and reset the debounce timer."""
                with self._lock:
                    self._pending.add(abs_path)
                    if self._timer is not None:
                        self._timer.cancel()
                    self._timer = threading.Timer(
                        _DEBOUNCE_SECONDS, self._flush
                    )
                    self._timer.start()

            def _flush(self):
                """Process all pending files after the debounce window."""
                with self._lock:
                    paths = list(self._pending)
                    self._pending.clear()
                    self._timer = None

                for abs_path in paths:
                    self._update_file(abs_path)

            def _update_file(self, abs_path: str):
                path = Path(abs_path)
                if not path.is_file():
                    return
                if path.is_symlink():
                    return
                if _is_binary(path):
                    return
                try:
                    source = path.read_bytes()
                    fhash = hashlib.sha256(source).hexdigest()
                    nodes, edges = parser.parse_bytes(path, source)
                    store.store_file_nodes_edges(abs_path, nodes, edges, fhash)
                    store.set_metadata(
                        "last_updated", time.strftime("%Y-%m-%dT%H:%M:%S")
                    )
                    store.commit()
                    rel = str(path.relative_to(repo_root))
                    logger.info(
                        "Updated: %s (%d nodes, %d edges)",
                        rel, len(nodes), len(edges),
                    )
                except Exception as e:
                    logger.error("Error updating %s: %s", abs_path, e)

        handler = GraphUpdateHandler()
        observer = Observer()
        observer.schedule(handler, str(repo_root), recursive=True)
        observer.start()

        logger.info("Watching %s for changes... (Ctrl+C to stop)", repo_root)
        try:
            import time as _time
            while True:
                _time.sleep(1)
        except KeyboardInterrupt:
            observer.stop()
        observer.join()
        logger.info("Watch stopped.")
    finally:
        _release_watch_lock(repo_root, owner_pid)


def start_watch_thread(
    repo_root: Path,
    store: GraphStore,
    daemon: bool = True,
) -> threading.Thread | None:
    """Start watch mode in a background thread.

    Returns the started thread, or None if watchdog is unavailable.
    """
    try:
        import watchdog  # noqa: F401
    except ImportError:
        logger.warning("watchdog not installed; auto-watch disabled")
        return None

    thread = threading.Thread(
        target=watch,
        args=(repo_root, store),
        daemon=daemon,
        name="crg-watch",
    )
    thread.start()
    logger.info("Auto-watch started for %s", repo_root)
    return thread


